name: dsm

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "centreon-dsm/**"
      - "!centreon-dsm/veracode.json"
      - "!centreon-dsm/.veracode-exclusions"
  push:
    branches:
      - develop
      - dev-[2-9][0-9].[0-9][0-9].x
      - master
      - "[2-9][0-9].[0-9][0-9].x"
    paths:
      - "centreon-dsm/**"
      - "!centreon-dsm/veracode.json"
      - "!centreon-dsm/.veracode-exclusions"

env:
  module: dsm

jobs:
  get-environment:
    uses: ./.github/workflows/get-environment.yml
    with:
      version_file: centreon-dsm/www/modules/centreon-dsm/conf.php

  backend-lint:
    runs-on: ubuntu-24.04
    needs: [get-environment]
    if: ${{ needs.get-environment.outputs.skip_workflow == 'false' }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@cf4cade2721270509d5b1c766ab3549210a39a2a # v2.33.0
        with:
          php-version: 8.2
          coverage: none
        env:
          runner: ubuntu-24.04

      - name: Install Dependencies
        run: composer install --optimize-autoloader
        working-directory: centreon-dsm
        shell: bash

      - name: Run of phpstan on /www at level 0
        run: vendor/bin/phpstan analyse --no-progress --level=0 --configuration=phpstan.neon
        working-directory: centreon-dsm
