name: open-tickets

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "centreon-open-tickets/**"
      - "!centreon-open-tickets/veracode.json"
      - "!centreon-open-tickets/.veracode-exclusions"
  push:
    branches:
      - develop
      - dev-[2-9][0-9].[0-9][0-9].x
      - master
      - "[2-9][0-9].[0-9][0-9].x"
    paths:
      - "centreon-open-tickets/**"
      - "!centreon-open-tickets/veracode.json"
      - "!centreon-open-tickets/.veracode-exclusions"

env:
  module: open-tickets

jobs:
  get-environment:
    uses: ./.github/workflows/get-environment.yml
    with:
      version_file: centreon-open-tickets/www/modules/centreon-open-tickets/conf.php

  backend-lint:
    runs-on: ubuntu-24.04
    needs: [get-environment]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@cf4cade2721270509d5b1c766ab3549210a39a2a # v2.33.0
        with:
          php-version: 8.2
          coverage: none
        env:
          runner: ubuntu-24.04

      - name: Install Dependencies
        run: composer install --optimize-autoloader
        working-directory: centreon-open-tickets
        shell: bash

      - name: Run of phpstan on /www at level 2
        run: vendor/bin/phpstan analyse --no-progress --level=2 --configuration=phpstan.neon
        working-directory: centreon-open-tickets

      - name: Run of phpstan on /src at level max
        run: vendor/bin/phpstan analyse --no-progress --level=9 --configuration=phpstan.core.neon
        working-directory: centreon-open-tickets

  backend-unit-test:
    runs-on: ubuntu-24.04
    needs: [get-environment]
    if: ${{ needs.get-environment.outputs.stability != 'stable' }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@cf4cade2721270509d5b1c766ab3549210a39a2a # v2.33.0
        with:
          php-version: 8.2
          coverage: none
        env:
          runner: ubuntu-24.04

      - name: Install dependencies
        uses: ramsey/composer-install@a2636af0004d1c0499ffca16ac0b4cc94df70565 # v3.1.0
        with:
          working-directory: centreon-open-tickets
          composer-options: "--optimize-autoloader"

      - name: Unit test
        run: XDEBUG_MODE=coverage composer run-script test:ci
        working-directory: centreon-open-tickets

      - if: failure()
        uses: ./.github/actions/publish-report
        with:
          path: "centreon/build/phpunit.xml"
          format: "php-junit"
