name: web
run-name: ${{ (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.nightly_manual_trigger == 'true')) && format('web nightly {0}', github.ref_name) || '' }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      nightly_manual_trigger:
        description: 'Set to true to trigger a nightly run'
        required: true
        default: false
        type: boolean
  schedule:
    - cron: "0 3 * * 1-5"
  pull_request:
    paths:
      - "centreon/**"
      - "!centreon/cypress/**"
      - "!centreon/features/**"
      - "!centreon/lighthouse/**"
      - "!centreon/tests/**"
      - "!centreon/.veracode-exclusions"
      - "!centreon/veracode.json"
      - "!centreon/packages/**"
  push:
    branches:
      - develop
      - dev-[2-9][0-9].[0-9][0-9].x
      - master
      - "[2-9][0-9].[0-9][0-9].x"
    paths:
      - "centreon/**"
      - "!centreon/cypress/**"
      - "!centreon/features/**"
      - "!centreon/lighthouse/**"
      - "!centreon/tests/**"
      - "!centreon/.veracode-exclusions"
      - "!centreon/veracode.json"
      - "!centreon/packages/**"

env:
  base_directory: centreon
  widgets_directory: centreon/www/widgets

jobs:
  changes:
    needs: [get-environment]
    runs-on: ubuntu-24.04
    outputs:
      has_frontend_changes: ${{ steps.filter.outputs.has_frontend_changes || 'true' }}
      has_backend_changes: ${{ steps.filter.outputs.has_backend_changes || 'true' }}
      has_test_changes: ${{ steps.filter.outputs.has_test_changes || 'true' }}
      has_upgrade_changes: ${{ steps.filter.outputs.has_upgrade_changes || 'true' }}
      trigger_delivery: ${{ steps.changes_trigger_checks.outputs.trigger_delivery }}
      trigger_api_testing: ${{ steps.changes_trigger_checks.outputs.trigger_api_testing }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        if: ${{ needs.get-environment.outputs.is_nightly == 'false' }}
        with:
          filters: |
            has_frontend_changes:
              - 'centreon/*.[jt]sx?'
              - 'centreon/!(*tests)/*.[jt]sx?'
              - 'centreon/www/front_src/**'
              - 'centreon/www/widgets/src/**'
              - 'centreon/package*'
              - 'centreon/lighthouse/**'
              - 'centreon/tsconfig.json'
              - 'centreon/cypress/**|**/pnpm-*'
            has_backend_changes:
              - 'centreon/*.php'
              - 'centreon/!(*tests)/*.php'
              - 'centreon/phpstan*.neon'
              - 'centreon/codingstyle.xml'
              - 'centreon/config/**/*.xml'
              - 'centreon/phpunit.xml'
              - 'centreon/ruleset.xml'
              - 'centreon/www/**/*.xml'
              - 'centreon/bin/**'
              - 'centreon/tmpl/**'
              - 'centreon/features/**'
              - 'centreon/src/**'
              - 'centreon/config/**'
              - 'centreon/composer.*'
              - 'centreon/www/!(front_src)/**'
              - 'centreon/doc/API/**'
            has_test_changes:
              - 'centreon/tests/**'
            has_upgrade_changes:
              - 'centreon/www/install/**'
              - 'centreon/packaging/**'
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - uses: ./.github/actions/changes-trigger-checks
        id: changes_trigger_checks
        with:
          is_nightly: ${{ needs.get-environment.outputs.is_nightly }}
          has_frontend_changes: ${{ steps.filter.outputs.has_frontend_changes || 'true' }}
          has_backend_changes: ${{ steps.filter.outputs.has_backend_changes || 'true' }}
          has_test_changes: ${{ steps.filter.outputs.has_test_changes || 'true' }}

  dispatch-to-maintained-branches:
    if: ${{ github.run_attempt == 1 && github.event_name == 'schedule' && github.ref_name == 'develop' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check current day of the week
        id: day_check
        run: echo "day_of_week=$(date +%u)" >> $GITHUB_OUTPUT
        shell: bash

      - if: ${{ steps.day_check.outputs.day_of_week == '1' }}
        run: |
          NIGHTLY_TARGETS=("dev-22.10.x" "dev-23.04.x" "dev-23.10.x" "dev-24.04.x" "dev-24.10.x")
          for target in "${NIGHTLY_TARGETS[@]}"; do
            echo "[INFO] - Dispatching nightly run to $target branch."
            gh workflow run web.yml -r "$target" -f nightly_manual_trigger=true
          done
        shell: bash
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  get-environment:
    uses: ./.github/workflows/get-environment.yml
    with:
      version_file: centreon/www/install/insertBaseConf.sql
      nightly_manual_trigger: ${{ inputs.nightly_manual_trigger || false }}

  gherkin-lint:
    runs-on: ubuntu-24.04
    needs: [get-environment, changes]
    if: ${{ needs.get-environment.outputs.skip_workflow == 'false' && needs.changes.outputs.has_test_changes == 'true' }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: ./.github/actions/gherkin-lint
        with:
          features_path: centreon/tests/e2e/features

  frontend-web-build:
    needs: [get-environment]
    if: ${{ needs.get-environment.outputs.skip_workflow == 'false' }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: ./.github/actions/frontend-build
        with:
          base_directory: ${{ env.base_directory }}
          dependencies_lock_file: ${{ env.base_directory }}/pnpm-lock.yaml
          index_file: ${{ env.base_directory }}/www/index.html
          static_directory: ${{ env.base_directory }}/www/static
          index_cache_key: ${{ github.sha }}-${{ github.run_id }}-index
          static_cache_key: ${{ github.sha }}-${{ github.run_id }}-static
          build_command: pnpm centreon:build

      - name: Create Jira ticket if nightly build failure
        if: |
          needs.get-environment.outputs.is_nightly == 'true' && github.run_attempt == 1 &&
          failure() &&
          startsWith(github.ref_name, 'dev')
        uses: ./.github/actions/create-jira-ticket
        with:
          jira_base_url: ${{ secrets.JIRA_BASE_URL }}
          jira_user_email: ${{ secrets.XRAY_JIRA_USER_EMAIL }}
          jira_api_token: ${{ secrets.XRAY_JIRA_TOKEN }}
          module_name: "centreon-web"
          ticket_labels: '["Nightly", "Pipeline", "nightly-${{ github.ref_name }}", "${{ github.job }}"]'

  backend-dependencies:
    needs: [get-environment]
    if: ${{ needs.get-environment.outputs.skip_workflow == 'false' }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@cf4cade2721270509d5b1c766ab3549210a39a2a # v2.33.0
        with:
          php-version: 8.2
        env:
          runner: ubuntu-24.04

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader
        working-directory: ${{ env.base_directory }}
        shell: bash

      - name: Cache vendor directory
        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ${{ env.base_directory }}/vendor
          key: ${{ github.sha }}-${{ github.run_id }}-vendor
